// <auto-generated />
using System;
using IBSYS.PPS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IBSYS.PPS.Migrations
{
    [DbContext(typeof(IbsysDatabaseContext))]
    partial class IbsysDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IBSYS.PPS.Models.BillOfMaterial", b =>
                {
                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductName");

                    b.ToTable("BillOfMaterials");
                });

            modelBuilder.Entity("IBSYS.PPS.Models.LaborAndMachineCosts", b =>
                {
                    b.Property<int>("Workplace")
                        .HasColumnType("int");

                    b.Property<double>("IdleTimeMachineCosts")
                        .HasColumnType("float");

                    b.Property<double>("LaborCostsFirstShift")
                        .HasColumnType("float");

                    b.Property<double>("LaborCostsOvertime")
                        .HasColumnType("float");

                    b.Property<double>("LaborCostsSecondShift")
                        .HasColumnType("float");

                    b.Property<double>("LaborCostsThirdShift")
                        .HasColumnType("float");

                    b.Property<double>("ProductiveMachineCosts")
                        .HasColumnType("float");

                    b.HasKey("Workplace");

                    b.ToTable("LaborAndMachineCosts");
                });

            modelBuilder.Entity("IBSYS.PPS.Models.Material", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BillOfMaterialProductName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentMaterialId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityNeeded")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BillOfMaterialProductName");

                    b.HasIndex("ParentMaterialId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("IBSYS.PPS.Models.Stock", b =>
                {
                    b.Property<string>("ItemNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ItemValue")
                        .HasColumnType("float");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<string>("Usage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemNumber");

                    b.ToTable("Stock");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Stock");
                });

            modelBuilder.Entity("IBSYS.PPS.Models.PurchasedItems", b =>
                {
                    b.HasBaseType("IBSYS.PPS.Models.Stock");

                    b.Property<double>("Deviation")
                        .HasColumnType("float");

                    b.Property<int>("DiscountQuantity")
                        .HasColumnType("int");

                    b.Property<double>("OrderCosts")
                        .HasColumnType("float");

                    b.Property<double>("ProcureLeadTime")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("PurchasedItems");
                });

            modelBuilder.Entity("IBSYS.PPS.Models.SelfProductionItems", b =>
                {
                    b.HasBaseType("IBSYS.PPS.Models.Stock");

                    b.HasDiscriminator().HasValue("SelfProductionItems");
                });

            modelBuilder.Entity("IBSYS.PPS.Models.Material", b =>
                {
                    b.HasOne("IBSYS.PPS.Models.BillOfMaterial", null)
                        .WithMany("RequiredMaterials")
                        .HasForeignKey("BillOfMaterialProductName");

                    b.HasOne("IBSYS.PPS.Models.Material", "ParentMaterial")
                        .WithMany("MaterialNeeded")
                        .HasForeignKey("ParentMaterialId");
                });
#pragma warning restore 612, 618
        }
    }
}
