apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-ingress-nginx-controller
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: nginx-ingress
    meta.helm.sh/release-namespace: ibsys-pps
data:
  proxy-buffer-size: "128k"
  proxy-buffers: "4 256k"
  proxy-read-timeout: "150"
  proxy-http-version: "1.1"
  client-header-buffer-size: "64k"
  large-client-header-buffers: "8 64k"
  allow-backend-server-header: "true"
  use-forwarded-headers: "true"
  compute-full-forwarded-for: "true"
  ignore-invalid-headers: "false"