apiVersion: apps/v1
kind: Deployment
metadata:
  name: pps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pps-backend
  template:
    metadata:
      labels:
        app: pps-backend
    spec:
      containers:
        - name: pps
          image: ibsys2registry2.azurecr.io/pps-backend-net5:v1.3
          env:
            - name: ASPNETCORE_URLS
              value: http://+
            - name: ASPNETCORE_ENVIRONMENT
              value: Kubernetes
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pps-backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: pps-backend
